# Generated by Django 3.2.8 on 2023-06-03 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_classes', models.IntegerField(verbose_name='№ занятия')),
                ('names', models.CharField(max_length=250, verbose_name='Наименование')),
                ('number_hours', models.IntegerField(verbose_name='Количество часов ')),
                ('task_independent_work', models.CharField(max_length=250, verbose_name='Задание самостоятельной работы')),
            ],
        ),
        migrations.CreateModel(
            name='Colleague',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=40, verbose_name='Фамилия')),
                ('fist_name', models.CharField(max_length=20, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=30, verbose_name='Отчество')),
                ('name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('telephone', models.CharField(max_length=12, verbose_name='Телефон')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=10, verbose_name='Индекс')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='FormAttestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=5, verbose_name='Номер')),
                ('year_receipt', models.DateField(verbose_name='Год поступления')),
                ('school_graduation_class', models.CharField(max_length=10, verbose_name='Класс окончания школы')),
                ('form_education', models.CharField(max_length=10, verbose_name='Форма обучения')),
                ('colleague', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='journal.colleague')),
            ],
        ),
        migrations.CreateModel(
            name='LevelPreparationPPCCZ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, verbose_name='Должность')),
            ],
        ),
        migrations.CreateModel(
            name='PreparationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_preparation_PPCCZ', models.CharField(max_length=5, verbose_name='Уровень подготовки ППССЗ')),
                ('number_educational_building', models.CharField(max_length=2, verbose_name='№ Учебного корпуса')),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=8, verbose_name='Код ')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fist_name', models.CharField(max_length=20, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=40, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=30, verbose_name='Отчество')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('place_residence', models.CharField(max_length=100, verbose_name='Место проживания')),
                ('place_registration', models.CharField(max_length=100, verbose_name='Место прописки')),
                ('telephone', models.CharField(max_length=12, verbose_name='Телефон')),
                ('number_personal_file', models.CharField(max_length=50, verbose_name='Личное дело')),
                ('year_receipt', models.DateField(verbose_name='Год поступления')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='GroupDisciplines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField(verbose_name='Семестр')),
                ('data_compilation', models.DateField(verbose_name='Дата составления')),
                ('work_interaction_teacher', models.IntegerField(verbose_name='Работа по взаимодействия с преподавателем(часов)')),
                ('total_hours_independent_work', models.IntegerField(verbose_name='Всего часов самостоятельных работ')),
                ('lab_practice_classes', models.IntegerField(verbose_name='Лабораторные или Практические занятия(часов)')),
                ('lab_division_subgroups', models.IntegerField(verbose_name='Лабораторные с делением на подгруппы(часов)')),
                ('course_design', models.IntegerField(verbose_name='Курсовое проектирование')),
                ('course_division_subgroups', models.IntegerField(verbose_name='Курсовые с делением на подгруппы(часов)')),
                ('design_course_projects', models.IntegerField(verbose_name='Проектирование курсовых проектов(часов) ')),
                ('consultations', models.IntegerField(verbose_name='Консультирование(часов)')),
                ('examination', models.IntegerField(verbose_name='Экзамен(часов)')),
                ('form_intermediate_certification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='journal.formattestation')),
                ('id_disciplines', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='journal.disciplines')),
                ('id_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='journal.group')),
                ('leading_teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='journal.colleague')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='journal.preparationplan'),
        ),
        migrations.AddField(
            model_name='group',
            name='speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='journal.speciality'),
        ),
        migrations.AddField(
            model_name='group',
            name='student',
            field=models.ManyToManyField(to='journal.Student'),
        ),
        migrations.CreateModel(
            name='EvaluationClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valuation', models.CharField(max_length=5, verbose_name='Оценка')),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.classes')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.student')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeHelpLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colleague', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.colleague')),
                ('group_disciplines', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.groupdisciplines')),
            ],
        ),
        migrations.AddField(
            model_name='colleague',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='journal.post'),
        ),
        migrations.AddField(
            model_name='classes',
            name='id_col_ruled_occupation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='journal.employeehelplesson'),
        ),
    ]
